---
ssh_private_workloads_key_file: "{{ playbook_dir }}/../secrets/compute"
ansible_ssh_user: ubuntu
ansible_ssh_common_args: >-
  -o ProxyCommand='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i {{ ansible_ssh_private_key_file }}
  -W %h:%p -p 22 -q {{ hostvars[groups["bastion_" + aws_vpc][0]]['ansible_user'] }}@{{ bastion }}'
  -i {{ ssh_private_workloads_key_file }}
